services:
  counter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./db:/app/db
    environment:
      PORT: 3000
      DATABASE_PATH: /app/db/counter.db
    restart: unless-stopped
